### ISSUE TITLE
[BUG] Typo for crc-support pusher action

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/ci-definitions#42]
```yaml
- name: Upload crc-support-tkn
        uses: actions/upload-artifact@v4
        with:
          name: crc-support-tkn
          path: crc-support/tkn/crc-support*
```

The task file name is task.yaml as so nothing is added to the artifact. This is only affecting the bundle push.
